### ISSUE TITLE
How can i give padding to my image

### ISSUE THREAD

**Issue by yogeshpaliyal** [hdodenhof/CircleImageView#267]
please review

**Comment by hdodenhof** [comment]
In the same way as with any other `View`: using `padding` XML attributes or `setPadding` methods.

**Comment by srujanb** [comment]
@hdodenhof  Actually the usual padding is not working as expected. My image was getting clipped because of the circular shape. I tried padding/margin etc but it is actually adding padding to the entire image view making it impossible to prevent your image getting clipped. If there arn't any workarounds for that, I might have to use alternate options for my circular imageview requirements.

**Comment by hdodenhof** [comment]
@srujanb I'm not sure what exactly you want to achieve but the whole point of this library is to efficiently clip an image to a circle. If you don't want the image to be clipped at all, you don't really need this.

**Comment by camrongiuliani** [comment]
@hdodenhof  I believe that @srujanb is trying to achieve the same thing I am.

This is what I want (prototype render):

<img width="133" alt="screen shot 2018-06-28 at 12 51 03 pm" src="https://user-images.githubusercontent.com/13203053/42048703-0813cfce-7ad2-11e8-9725-14f029f3f948.png">

And this is what I am getting with this library:
<img width="154" alt="screen shot 2018-06-28 at 12 53 35 pm" src="https://user-images.githubusercontent.com/13203053/42048801-4cfb6cfa-7ad2-11e8-85fb-be73842001d0.png">

Notice how my image (a calendar icon) has no padding around it. Due to this being CENTER_CROP, it would be nice to be able to pad the images.

Would this be possible?

Thanks for this library!

**Comment by hdodenhof** [comment]
@camrongiuliani using this library for what you want to achieve would be very inefficient (and is currently impossible).

As you don't want to crop your image at all, I'd go with the following approach:
1. Define a ShapeDrawable in `res/drawable`, e.g. `oval.xml`:
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <stroke
        android:width="1dp"
        android:color="#FFFFFF"/>
</shape>
```

2. Use that shape drawable as a background for a regular image view and give it some padding:
```
<ImageView
    android:layout_width="160dp"
    android:layout_height="160dp"
    android:padding="48dp"
    android:layout_centerInParent="true"
    android:src="@drawable/calendar" 
    android:background="@drawable/oval"/>
```

Another approach would be using a `LayerDrawable` with the circle shape on the bottom layer and your icon above.

**Comment by camrongiuliani** [comment]
@hdodenhof thank you for the hasty response, and providing a better solution for my use case!

**Comment by Aditya7521** [comment]
You can use 

app:civ_border_color="@color/white"
app:civ_border_width="5dp"

to make it look like a padding
