### ISSUE TITLE
OnClick() 

### ISSUE THREAD

**Issue by vgomwork** [hdodenhof/CircleImageView#276]
When i try to use the property android:onClick in XML, i got Excepcion"but got android.support.v7.view.ContextThemeWrapper". Is not compatible with de onClick listener of the View parent?

**Comment by hdodenhof** [comment]
With that incomplete exception it is impossible to say what exactly is going on, but I doubt your issue is caused by this library. Please replace the `CircleImageView` in your layout with a regular `ImageView` - if the issue persists, head over to StackOverflow for general help. If not, reopen this issue with more details.
