### ISSUE TITLE
TransitionDrawable support

### ISSUE THREAD

**Issue by carriehall** [hdodenhof/CircleImageView#369]
I am getting the same exception as others when I try to use a transition drawable

`java.lang.IllegalArgumentException: width and height must be > 0`

I believe it's caused by these lines

```
if (drawable instanceof ColorDrawable) {
     bitmap = Bitmap.createBitmap(COLORDRAWABLE_DIMENSION, COLORDRAWABLE_DIMENSION, BITMAP_CONFIG);
} else {
     bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), BITMAP_CONFIG);
}
```

TransitionDrawables are returning -1 for the intrinsic sizes, presumably because I am creating them on the fly as they are used for a Picasso placeholder rather than inflated onto the screen already.

If I use a custom class and override `getIntrinsicWidth` and `getIntrinsicHeight` with 1, then it seems to work, but it feels hacky and I'm not sure what the repercussions are.

**Comment by hdodenhof** [comment]
While there's no proper support for TransitionDrawables, your issue is not directly related to that. The intrinsic size of a `TransitionDrawable` is calculated using the intrinsic sizes of the Drawables it wraps, so it seems that in your case it's just that all layers have an intrinsic sizes of `-1`. What types of Drawables are you using to construct the `TransitionDrawable`?

You should now that even if you work around the intrinsic size issue, you won't see any actual transition happening, this is a [limitation](https://github.com/hdodenhof/CircleImageView#limitations) of the current implementation. There's an open PR (#236) to address this which seems to work but I haven't gotten around to fully verify it's behavior and memory consumption implications yet.

**Comment by carriehall** [comment]
Thanks for the clarification, the drawables I'm using in the layers are ColorDrawables so maybe that would also explain why the intrinsic sizes aren't set.

**Comment by hdodenhof** [comment]
Yep, that explains it. In that special case it would be fine to use hardcoded intrinsic dimensions for your `TransitionDrawable`. You'd want to use `2` though as `1` doesn't work on some Android versions (see #23).

As or the actual transition: I just did some work on supporting it in `feature/transition-drawable-support` - feel free to give it a try.

**Comment by carriehall** [comment]
I hardcoded the dimensions and it seems to work, thanks!
